---------- KISIYE GORE SIPARIS BILGILERI ----------

SELECT
    U.USERNAME_, 
    U.NAMESURNAME, 
    CT.CITY,
    T.TOWN, 
    D.DISTRICT, 
    A.ADDRESSTEXT,
    O.ID AS ORDER_ID, 
    O.TOTALPRICE, 
    O.DATE_ AS ORDER_DATE,
    P.DATE_ AS PAYMENT_DATE,
    P.APPROVECODE, 
    I.DATE_ AS INVOICE_DATE, 
    I.CARGOFICHENO

FROM ORDERS O
    INNER JOIN USERS U ON U.ID = O.USERID
    INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
    INNER JOIN CITIES CT ON CT.ID = A.CITYID
    INNER JOIN TOWNS T ON T.ID = A.TOWNID
    INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
    LEFT JOIN PAYMENTS P ON P.ORDERID = O.ID
    LEFT JOIN INVOICES I ON I.ORDERID = O.ID

WHERE U.NAMESURNAME = 'Soner ÜLGEN'   ----------> VERISI CEKILMEK ISTENEN KISI
ORDER BY O.DATE_ DESC;


---------- GUNLERE GORE SIPARIS DAGILIMI ----------

SELECT
    CONVERT(DATE, O.DATE_) AS TARIH,
    SUM(OD.LINETOTAL) AS TOPLAM_SIPARIS_TUTARI,
    SUM(OD.AMOUNT) AS TOPLAM_SIPARIS_MIKTARI,
    COUNT(OD.ID) AS TOPLAM_SIPARIS_SAYISI

FROM ORDERS O
    INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID

GROUP BY CONVERT(DATE, O.DATE_)
ORDER BY TARIH ASC;


---------- AYLARA GORE SIPARIS DETAYLARI ----------

SELECT
    DATEPART(YEAR, O.DATE_) AS YIL,
    DATEPART(MONTH, O.DATE_) AS AY,
    CASE DATEPART(MONTH, O.DATE_)
        WHEN 1 THEN 'OCAK'                  
        WHEN 2 THEN 'SUBAT'
        WHEN 3 THEN 'MART'
        WHEN 4 THEN 'NISAN'
        WHEN 5 THEN 'MAYIS'
        WHEN 6 THEN 'HAZIRAN'
        WHEN 7 THEN 'TEMMUZ'     
        WHEN 8 THEN 'AGUSTOS'
        WHEN 9 THEN 'EYLUL'
        WHEN 10 THEN 'EKIM'
        WHEN 11 THEN 'KASIM'
        WHEN 12 THEN 'ARALIK'
    END AS AY_ADI,
    SUM(OD.LINETOTAL) AS TOPLAM_SIPARIS_TUTARI,
    SUM(OD.AMOUNT) AS TOPLAM_SIPARIS_MIKTARI,
    COUNT(OD.ID) AS TOPLAM_SIPARIS_SAYISI

FROM ORDERS O
    INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID

GROUP BY DATEPART(YEAR, O.DATE_), DATEPART(MONTH, O.DATE_)
ORDER BY YIL ASC, AY ASC;


---------- URUN FIYAT METRIKLERI (MAX, MIN, AVG) ----------

SELECT	
    ITM.ITEMCODE AS URUN_KODU,
    ITM.ITEMNAME AS URUN_ADI,
    MAX(OD.UNITPRICE) AS MAX_FIYAT,
    MIN(OD.UNITPRICE) AS MIN_FIYAT,
    ROUND(AVG(OD.UNITPRICE), 2) AS ORTALAMA_FIYAT

FROM ITEMS ITM
    LEFT JOIN ORDERDETAILS OD ON OD.ITEMID = ITM.ID

GROUP BY ITM.ITEMCODE, ITM.ITEMNAME
ORDER BY ITM.ITEMCODE;


---------- PARETO DILIMI HESAPLAMA ----------


WITH MUSTERI_HARCAMALARI AS (
    SELECT 
        U.ID AS KULLANICI_ID,
        U.NAMESURNAME AS AD_SOYAD,
        SUM(O.TOTALPRICE) AS TOPLAM_HARCAMA
    FROM USERS U
    INNER JOIN ORDERS O ON U.ID = O.USERID
    GROUP BY U.ID, U.NAMESURNAME),

KUMULATIF_HESAPLAMA AS (
    
    SELECT
        KULLANICI_ID,
        AD_SOYAD,
        TOPLAM_HARCAMA,
        SUM(TOPLAM_HARCAMA) OVER (
            ORDER BY TOPLAM_HARCAMA DESC 
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS KUMULATIF_TOPLAM,       
        SUM(TOPLAM_HARCAMA) OVER () AS GENEL_CIRO

    FROM MUSTERI_HARCAMALARI
    )

SELECT
    KULLANICI_ID,
    AD_SOYAD,
    ROUND(TOPLAM_HARCAMA, 2) AS TOPLAM_HARCAMA,
    ROUND(KUMULATIF_TOPLAM, 2) AS KUMULATIF_TOPLAM,
    ROUND((KUMULATIF_TOPLAM / GENEL_CIRO) * 100, 2) AS KUMULATIF_CIRO_ORANI,
    CASE
        WHEN (KUMULATIF_TOPLAM / GENEL_CIRO) <= 0.80 THEN 'CİRONUN %80''İNİ GETİRENLER (PARETO DİLİMİ)'
        ELSE 'KALAN %20''LİK MÜŞTERİ GRUBU'
    END AS PARETO_SINIFLANDIRMASI

FROM KUMULATIF_HESAPLAMA

ORDER BY TOPLAM_HARCAMA DESC;